# OpenAI secrets
OPENAI_API_KEY = "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"

# Astra DB secrets
ASTRA_API_ENDPOINT = "https://ac67cdf1-c0cc-461a-a13a-5b4e5fa0be17-us-east-1.apps.astra.datastax.com"
ASTRA_TOKEN = "AstraCS:HKfCWCUIrQYSuCWFqgJmnXCH:93e915b0b6f8589d22475d1dbe8f642d2ea2d55b69b35e7508c62d4ef9014b4d"
